{"spans": [{"name": "get_weather_models", "context": {"span_id": "0xd0ad2c5dbb37ba49", "trace_id": "0x6bc9114ab53c46532c71848cd9efebbc"}, "parent_id": null, "start_time": 1737519126218903000, "end_time": 1737519126332063000, "status_code": "ERROR", "status_message": "JSONDecodeError: Expecting value: line 1 column 1 (char 0)", "attributes": {"mlflow.traceRequestId": "\"3e19919082904c49aac5ef6a53f04dbd\"", "mlflow.spanType": "\"TOOL\"", "mlflow.spanFunctionName": "\"get_weather_models\"", "mlflow.spanInputs": "{}"}, "events": [{"name": "exception", "timestamp": 1737519126332011000, "attributes": {"exception.type": "json.decoder.JSONDecodeError", "exception.message": "Expecting value: line 1 column 1 (char 0)", "exception.stacktrace": "Traceback (most recent call last):\n  File \"/Users/mashhood/.mlflow/envs/mlflow-715d011a4178d874cb0fa1367491deb43b9ab6fd/lib/python3.11/site-packages/opentelemetry/trace/__init__.py\", line 589, in use_span\n    yield span\n  File \"/Users/mashhood/.mlflow/envs/mlflow-715d011a4178d874cb0fa1367491deb43b9ab6fd/lib/python3.11/site-packages/mlflow/tracing/fluent.py\", line 272, in start_span\n    yield mlflow_span\n  File \"/Users/mashhood/.mlflow/envs/mlflow-715d011a4178d874cb0fa1367491deb43b9ab6fd/lib/python3.11/site-packages/mlflow/tracing/fluent.py\", line 145, in _wrapping_logic\n    result = yield  # sync/async function output to be sent here\n             ^^^^^\n  File \"/Users/mashhood/.mlflow/envs/mlflow-715d011a4178d874cb0fa1367491deb43b9ab6fd/lib/python3.11/site-packages/mlflow/tracing/fluent.py\", line 175, in wrapper\n    return wrapping_coro.send(fn(*args, **kwargs))\n                              ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/mashhood/Documents/Hackathons/UOttahack 7/uOttaHack7/generated_agent.py\", line 129, in get_weather_models\n    data = json.loads(response.text)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/mashhood/.pyenv/versions/3.11.5/lib/python3.11/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/mashhood/.pyenv/versions/3.11.5/lib/python3.11/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/mashhood/.pyenv/versions/3.11.5/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n", "exception.escaped": "False"}}]}], "request": "{}", "response": null}